
services:

  node_1:
    extends:
     file: base-docker-compose.yml
     service: base-node
    container_name: node_1
    command: python main.py -np 8650
    environment:
      PEER_ID: 0

  node_2:
    extends:
     file: base-docker-compose.yml
     service: base-node
    container_name: node_2
    command: python main.py -np 8650 -i node_1 -p 8650
    environment:
      PEER_ID: 1

  node_3:
    extends:
     file: base-docker-compose.yml
     service: base-node
    container_name: node_3
    command: python main.py -np 8650 -i node_1 -p 8650
    environment:
      PEER_ID: 2


  node_4:
    extends:
     file: base-docker-compose.yml
     service: base-node
    container_name: node_4
    command: python main.py -np 8650 -i node_1 -p 8650
    environment:
      PEER_ID: 3

  node_5:
    extends:
     file: base-docker-compose.yml
     service: base-node
    container_name: node_5
    command: python main.py -np 8650 -i node_1 -p 8650
    environment:
      PEER_ID: 4

  node_6:
    extends:
     file: base-docker-compose.yml
     service: base-node
    container_name: node_6
    command: python main.py -np 8650 -i node_1 -p 8650
    environment:
      PEER_ID: 5


  node_7:
    extends:
     file: base-docker-compose.yml
     service: base-node
    container_name: node_7
    command: python main.py -np 8650 -i node_1 -p 8650
    environment:
      PEER_ID: 6

  node_8:
    extends:
     file: base-docker-compose.yml
     service: base-node
    container_name: node_8
    command: python main.py -np 8650 -i node_1 -p 8650
    environment:
      PEER_ID: 7

  node_9:
    extends:
     file: base-docker-compose.yml
     service: base-node
    container_name: node_9
    command: python main.py -np 8650 -i node_1 -p 8650
    environment:
      PEER_ID: 8

  node_10:
    extends:
     file: base-docker-compose.yml
     service: base-node
    container_name: node_10
    command: python main.py -np 8650 -i node_1 -p 8650
    environment:
      PEER_ID: 9